env:
 - GHCVER=7.10.3

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:$PATH

install:
 - cabal --version
 - cabal update
 - cabal install --enable-tests --enable-benchmarks --only-dependencies
 - cabal install hpc-coveralls

script:
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal test

# - cabal check
# - cabal sdist
# - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
#   cd dist/;
#   if [ -f "$SRC_TGZ" ]; then
#      cabal install "$SRC_TGZ";
#   else
#      echo "expected '$SRC_TGZ' not found";
#      exit 1;
#   fi

after_script:
   ~/.cabal/bin/hpc-coveralls test-all --display-report --repo-token=15KpYJ4FssvAiuhg5OBivEQbPYPn6aMSW
